### ISSUE TITLE
some functions not working

### ISSUE THREAD

**Issue by Tempokgs** [RADIUSdesk/rdcore#24]
Hello!
when executing the command:
/var/www/rdcore/cake4/rd_cake/bin# ./cake accounting
I get an error:
`Test the usertype of den
den is a Permanent User
=============================-=
--Find potential counters for--
-------400mb day 5mbits---------
______________________________
Array
(
    [cap] => hard
    [reset] => daily
    [value] => 419430400
    [reset_interval] =>
    [mac_counter] =>
)
Start at midnightSELECT IFNULL(SUM(acctinputoctets)+ SUM(acctoutputoctets),0) as used FROM radacct WHERE username='den' AND UNIX_TIMESTAMP(acctstarttime) + acctsessiontime > '1670976000'2 Update usage percentage for den to 0
2022-12-14 12:56:11 error: [Error] Call to a member function getData() on null in /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php on line 589
Stack Trace:
- /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php:426
- /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php:334
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventManager.php:309
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventManager.php:286
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php:92
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:2024
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:1990
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:1883
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:1570
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Database/Connection.php:709
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:1571
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php:1884
- /var/www/rdcore/cake4/rd_cake/src/Shell/AccountingShell.php:254
- /var/www/rdcore/cake4/rd_cake/src/Shell/AccountingShell.php:33
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/Shell.php:514
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/CommandRunner.php:352
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/CommandRunner.php:169
- /var/www/rdcore/cake4/rd_cake/bin/cake.php:12

[Error] Call to a member function getData() on null in /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php on line 589

Stack Trace:

#0 /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php(426): App\Model\Behavior\FreeRadiusBehavior->_forPermanentUserEdit()
#1 /var/www/rdcore/cake4/rd_cake/src/Model/Behavior/FreeRadiusBehavior.php(334): App\Model\Behavior\FreeRadiusBehavior->_doAfterSave()
#2 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventManager.php(309): App\Model\Behavior\FreeRadiusBehavior->afterSave()
#3 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventManager.php(286): Cake\Event\EventManager->_callListener()
#4 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(92): Cake\Event\EventManager->dispatch()
#5 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(2024): Cake\ORM\Table->dispatchEvent()
#6 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(1990): Cake\ORM\Table->_onSaveSuccess()
#7 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(1883): Cake\ORM\Table->_processSave()
#8 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(1570): Cake\ORM\Table->Cake\ORM\{closure}()
#9 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Database/Connection.php(709): Cake\ORM\Table->Cake\ORM\{closure}()
#10 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(1571): Cake\Database\Connection->transactional()
#11 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Table.php(1884): Cake\ORM\Table->_executeTransaction()
#12 /var/www/rdcore/cake4/rd_cake/src/Shell/AccountingShell.php(254): Cake\ORM\Table->save()
#13 /var/www/rdcore/cake4/rd_cake/src/Shell/AccountingShell.php(33): App\Shell\AccountingShell->process_username()
#14 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/Shell.php(514): App\Shell\AccountingShell->main()
#15 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/CommandRunner.php(352): Cake\Console\Shell->runCommand()
#16 /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Console/CommandRunner.php(169): Cake\Console\CommandRunner->runShell()
#17 /var/www/rdcore/cake4/rd_cake/bin/cake.php(12): Cake\Console\CommandRunner->run()
#18 {main}

`

also does not display % used traffic volume and is not shown on the client's page as well as the total volume.

`2022-12-14 11:00:16 error: [Cake\ORM\Exception\MissingTableClassException] Table class for alias `MacUsages` could not be found. in /var/www/rdcore/c
ake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php on line 243
Exception Attributes: array (
  0 => 'for alias `MacUsages`',
)
Stack Trace:
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Datasource/Locator/AbstractLocator.php:68
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:205
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Datasource/ModelAwareTrait.php:128
- /var/www/rdcore/cake4/rd_cake/src/Controller/RadacctsController.php:52
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/Controller.php:547
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:139
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:114
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php:320
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:77
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:157
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:186
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:77
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:131
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Server.php:90
- /var/www/rdcore/cake4/rd_cake/webroot/index.php:40
- /var/www/rdcore/cake4/rd_cake/index.php:16

Request URL: /radaccts/get_usage.json?username=slava&mac=D0-57-xx-xx-xx-xx
Referer URL: http://100.64.0.1/login/bootstrap5/index.html?res=notyet&uamip=100.64.0.1&uamport=3990&challenge=f2d8cb42582368f15ba193406f2e204f&called
=00-15-xx-xx-xx-xx&mac=D0-57-xx-xx-xx-xx&ip=1.64.0.11&ssid=Hotspot&nasid=HotSpot&sessionid=167099514500000001&userurl=http%3a%2f%2fwww.msftconn
ecttest.com%2fredirect&md=CFC83A3921DD42832729FF5220B79BDC&i18n=en_GB
Client IP: 1.64.0.11`

and also the flows button doesn't work

2022-12-13 09:01:56 error: [BadMethodCallException] Unknown method "schema" called on App\Model\Table\SoftflowsTable in /var/www/rdcore/cake4/rd_cake
/vendor/cakephp/cakephp/src/ORM/Table.php on line 2656
Stack Trace:
- /var/www/rdcore/cake4/rd_cake/src/Controller/SoftflowsController.php:90
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/Controller.php:547
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:139
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:114
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php:320
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:77
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php:157
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:186
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:77
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:131
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php:60
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /var/www/rdcore/cake4/rd_cake/vendor/cakephp/cakephp/src/Http/Server.php:90
- /var/www/rdcore/cake4/rd_cake/webroot/index.php:40
- /var/www/rdcore/cake4/rd_cake/index.php:16

Request URL: /softflows/index.json?_dc=1670922116526&dynamic_client_id=45&timespan=now&timezone_id=23&page=1&start=0&limit=50&token=b4c6ac81-8c7c-48
02-b50a-0a6380555b50&sel_language=4_4&cloud_id=23
Referer URL: http://10.1.1.1/
Client IP: 10.4.8.2

tell me how to fix.

**Comment by elgibor-solution** [comment]
+1 Got same issue
